server:
  port: 9020

spring:
  application:
    name: order-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    prefer-ip-address: true # 使用IP地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5 # 向Eureka发送心跳的间隔时间
    lease-expiration-duration-in-seconds: 10 # 多少秒之后Eureka没有收到微服务的心跳认为服务已经宕机
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka

# 暴露刷新的端点
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh


logging:
  level:
    root: warn