server:
  port: 9020

spring:
  application:
    name: order-service

eureka:
  instance:
    prefer-ip-address: true # 使用IP地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5 # 向Eureka发送心跳的间隔时间
    lease-expiration-duration-in-seconds: 10 # 多少秒之后Eureka没有收到微服务的心跳认为服务已经宕机
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka


feign:
  hystrix:
    enabled: true

ribbon:
  MaxAutoRetries: 1 # 同一台实例最大重试次数,不包括首次调用，当Eureka中可以找到服务，但是服务连不上时将会重试
  MaxAutoRetriesNextServer: 1 # 重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false # 对所有的操作请求都进行重试，如果是get则可以，如果是post,put等操作没有实现幂等的情况下是很危险的，所以设置为false
  ConnectTimeout: 1000 # 请求连接的超时时间
  ReadTimeout: 10000 # 请求处理的超时时间

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true # 开启超时熔断, 如果为false, 则熔断机制只在服务不可用时开启
        isolation:
          thread:
            timeoutInMilliseconds: 4000
