server:
  port: 9020

spring:
  application:
    name: order-web
  cloud:
    sentinel:
      eager: true
      transport:
        dashboard: localhost:8080
      datasource:
        ds1:
          file:
            file: classpath:flowrule.json # 加载流控规则配置
            data-type: json
            rule-type: flow
  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1 # 采样比 0 - 1，1表示采样所有日志，0.1表示采样10%的日志
  rabbitmq:
    host: localhost
    port: 5672
    listener: # 重试策略
      direct:
        retry:
          enabled: true
      simple:
        retry:
          enabled: true
feign:
  sentinel:
    enabled: true # 开启对feign的支持

eureka:
  instance:
    prefer-ip-address: true # 使用IP地址注册
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka

logging:
  level:
    root: error
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.cloud.sleuth: debug
